// Autogenerated by the Generate Class from Layout plugin, version 0.3.0
// Layout file: UI/AddonLine.layout

class SCR_WorkshopAddonLineWidgets
{
	static const ResourceName s_sLayout = "{1E9609F84FF1BF73}UI/AddonLine.layout";
	ResourceName GetLayout() { return s_sLayout; }

	ImageWidget m_LineBackground;

	ButtonWidget m_MoveLeftButton;
	SCR_ModularButtonComponent m_MoveLeftButtonComponent;

	ButtonWidget m_ActionButton;
	SCR_ModularButtonComponent m_ActionButtonComponent;

	TextWidget m_NameText;

	TextWidget m_StateText;

	ButtonWidget m_DeleteButton;
	SCR_ModularButtonComponent m_DeleteButtonComponent;

	ButtonWidget m_OpenDetailsButton;
	SCR_ModularButtonComponent m_OpenDetailsButtonComponent;

	ButtonWidget m_MoveRightButton;
	SCR_ModularButtonComponent m_MoveRightButtonComponent;

	bool Init(Widget root)
	{
		m_LineBackground = ImageWidget.Cast(root.FindWidget("LineHeight.Overlay.LineContent.m_LineBackground"));

		m_MoveLeftButton = ButtonWidget.Cast(root.FindWidget("LineHeight.Overlay.LineContent.LineElements.m_MoveLeftButton"));
		m_MoveLeftButtonComponent = SCR_ModularButtonComponent.Cast(m_MoveLeftButton.FindHandler(SCR_ModularButtonComponent));

		m_ActionButton = ButtonWidget.Cast(root.FindWidget("LineHeight.Overlay.LineContent.LineElements.m_ActionButton"));
		m_ActionButtonComponent = SCR_ModularButtonComponent.Cast(m_ActionButton.FindHandler(SCR_ModularButtonComponent));

		m_NameText = TextWidget.Cast(root.FindWidget("LineHeight.Overlay.LineContent.LineElements.m_NameText"));

		m_StateText = TextWidget.Cast(root.FindWidget("LineHeight.Overlay.LineContent.LineElements.m_StateText"));

		m_DeleteButton = ButtonWidget.Cast(root.FindWidget("LineHeight.Overlay.LineContent.LineElements.m_DeleteButton"));
		m_DeleteButtonComponent = SCR_ModularButtonComponent.Cast(m_DeleteButton.FindHandler(SCR_ModularButtonComponent));

		m_OpenDetailsButton = ButtonWidget.Cast(root.FindWidget("LineHeight.Overlay.LineContent.LineElements.m_OpenDetailsButton"));
		m_OpenDetailsButtonComponent = SCR_ModularButtonComponent.Cast(m_OpenDetailsButton.FindHandler(SCR_ModularButtonComponent));

		m_MoveRightButton = ButtonWidget.Cast(root.FindWidget("LineHeight.Overlay.LineContent.LineElements.m_MoveRightButton"));
		m_MoveRightButtonComponent = SCR_ModularButtonComponent.Cast(m_MoveRightButton.FindHandler(SCR_ModularButtonComponent));

		return true;
	}
}
