// Autogenerated by the Generate Class from Layout plugin, version 0.3.0
// Layout file: UI/Dialogs/ConfigurableDialog_Tools.layout

class WEXT_ConfigurableDialog_ToolsWidgets
{
	static const ResourceName s_sLayout = "{3D8774B818C15FA2}UI/Dialogs/ConfigurableDialog_Tools.layout";
	ResourceName GetLayout() { return s_sLayout; }

	ButtonWidget m_GenerateDsJsonButton;
	SCR_ModularButtonComponent m_GenerateDsJsonButtonComponent;

	ButtonWidget m_GenerateCliButton;
	SCR_ModularButtonComponent m_GenerateCliButtonComponent;

	bool Init(Widget root)
	{
		m_GenerateDsJsonButton = ButtonWidget.Cast(root.FindWidget("DialogBase0.VerticalLayout.Content.ContentSizeConstraints.ContentVerticalLayout.m_GenerateDsJsonButton"));
		m_GenerateDsJsonButtonComponent = SCR_ModularButtonComponent.Cast(m_GenerateDsJsonButton.FindHandler(SCR_ModularButtonComponent));

		m_GenerateCliButton = ButtonWidget.Cast(root.FindWidget("DialogBase0.VerticalLayout.Content.ContentSizeConstraints.ContentVerticalLayout.m_GenerateCliButton"));
		m_GenerateCliButtonComponent = SCR_ModularButtonComponent.Cast(m_GenerateCliButton.FindHandler(SCR_ModularButtonComponent));

		return true;
	}
}
