// Autogenerated by the Generate Class from Layout plugin, version 0.3.0
// Layout file: UI/Dialogs/AddonPresetDialog.layout

class WEXT_AddonPresetDialogWidgets
{
	static const ResourceName s_sLayout = "{F3DD4756F4081672}UI/Dialogs/AddonPresetDialog.layout";
	ResourceName GetLayout() { return s_sLayout; }

	ButtonWidget m_PresetNameEditbox;
	SCR_EditBoxComponent m_PresetNameEditboxComponent;

	ButtonWidget m_SaveButton;
	SCR_ModularButtonComponent m_SaveButtonComponent;

	OverlayWidget m_PresetNamesListbox;
	SCR_ListBoxComponent m_PresetNamesListboxComponent;

	ButtonWidget m_LoadButton;
	SCR_ModularButtonComponent m_LoadButtonComponent;

	ButtonWidget m_OverrideButton;
	SCR_ModularButtonComponent m_OverrideButtonComponent;

	ButtonWidget m_DeleteButton;
	SCR_ModularButtonComponent m_DeleteButtonComponent;

	ButtonWidget m_DisableAllButton;
	SCR_ModularButtonComponent m_DisableAllButtonComponent;

	bool Init(Widget root)
	{
		m_PresetNameEditbox = ButtonWidget.Cast(root.FindWidget("DialogBase0.VerticalLayout.Content.VerticalLayout0.SaveNewPreset.m_PresetNameEditbox"));
		m_PresetNameEditboxComponent = SCR_EditBoxComponent.Cast(m_PresetNameEditbox.FindHandler(SCR_EditBoxComponent));

		m_SaveButton = ButtonWidget.Cast(root.FindWidget("DialogBase0.VerticalLayout.Content.VerticalLayout0.SaveNewPreset.m_SaveButton"));
		m_SaveButtonComponent = SCR_ModularButtonComponent.Cast(m_SaveButton.FindHandler(SCR_ModularButtonComponent));

		m_PresetNamesListbox = OverlayWidget.Cast(root.FindWidget("DialogBase0.VerticalLayout.Content.VerticalLayout0.ListBoxAndButtons.ListSize.m_PresetNamesListbox"));
		m_PresetNamesListboxComponent = SCR_ListBoxComponent.Cast(m_PresetNamesListbox.FindHandler(SCR_ListBoxComponent));

		m_LoadButton = ButtonWidget.Cast(root.FindWidget("DialogBase0.VerticalLayout.Content.VerticalLayout0.ListBoxAndButtons.Buttons.m_LoadButton"));
		m_LoadButtonComponent = SCR_ModularButtonComponent.Cast(m_LoadButton.FindHandler(SCR_ModularButtonComponent));

		m_OverrideButton = ButtonWidget.Cast(root.FindWidget("DialogBase0.VerticalLayout.Content.VerticalLayout0.ListBoxAndButtons.Buttons.m_OverrideButton"));
		m_OverrideButtonComponent = SCR_ModularButtonComponent.Cast(m_OverrideButton.FindHandler(SCR_ModularButtonComponent));

		m_DeleteButton = ButtonWidget.Cast(root.FindWidget("DialogBase0.VerticalLayout.Content.VerticalLayout0.ListBoxAndButtons.Buttons.m_DeleteButton"));
		m_DeleteButtonComponent = SCR_ModularButtonComponent.Cast(m_DeleteButton.FindHandler(SCR_ModularButtonComponent));

		m_DisableAllButton = ButtonWidget.Cast(root.FindWidget("DialogBase0.VerticalLayout.Footer.m_DisableAllButton"));
		m_DisableAllButtonComponent = SCR_ModularButtonComponent.Cast(m_DisableAllButton.FindHandler(SCR_ModularButtonComponent));

		return true;
	}
}
